#!/bin/bash
# /etc/init.d/pi-alarm

### BEGIN INIT INFO
# Provides:          pi-alarm
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage the alarm
### END INIT INFO


case "$1" in 
    start)
        echo "Starting pi-alarm"
        /home/pi/pi_alarm.py &
        ;;
    stop)
        echo "Stopping pi-alarm"
        killall pi_alarm.py
        ;;
    *)
        echo "Usage: /etc/init.d/pi-alarm start|stop"
        exit 1
        ;;
esac


exit 0
